-- Supabase Schema for Paper Trading Application

-- Table for storing paper trades
CREATE TABLE IF NOT EXISTS paper_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_id UUID UNIQUE NOT NULL,
    strategy TEXT,
    instrument_key TEXT NOT NULL,
    side TEXT NOT NULL CHECK (side IN ('BUY', 'SELL')),
    quantity INTEGER NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    entry_price DOUBLE PRECISION NOT NULL,
    status TEXT DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED')),
    entry_rule TEXT,
    exit_time TIMESTAMPTZ,
    exit_price DOUBLE PRECISION,
    exit_rule TEXT,
    realized_pnl DOUBLE PRECISION DEFAULT 0.0,
    trade_duration_minutes INTEGER,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for storing current paper positions
CREATE TABLE IF NOT EXISTS paper_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_key TEXT UNIQUE NOT NULL,
    net_quantity INTEGER NOT NULL,
    avg_entry_price DOUBLE PRECISION NOT NULL,
    current_ltp DOUBLE PRECISION DEFAULT 0.0,
    unrealized_pnl DOUBLE PRECISION DEFAULT 0.0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for daily trading summary
CREATE TABLE IF NOT EXISTS daily_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE UNIQUE NOT NULL,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    realized_pnl DOUBLE PRECISION DEFAULT 0.0,
    max_drawdown_pct DOUBLE PRECISION DEFAULT 0.0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table for storing market data snapshots
CREATE TABLE IF NOT EXISTS market_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_key TEXT NOT NULL,
    ltp DOUBLE PRECISION,
    bid DOUBLE PRECISION,
    ask DOUBLE PRECISION,
    volume INTEGER,
    oi INTEGER,
    iv DOUBLE PRECISION,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Index for faster queries on market data
CREATE INDEX IF NOT EXISTS idx_market_data_instrument_timestamp ON market_data (instrument_key, timestamp);

-- Enable Row Level Security (RLS) - Note: You may want to disable this for simple private setups or configure specific policies.
-- ALTER TABLE paper_trades ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE paper_positions ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE daily_summary ENABLE ROW LEVEL SECURITY;
